name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: windows-latest
    env:
      src-dir: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v1.0.0
      id: script
      with:
        script: |
          Write-Host "Downloading"
          Import-Module BitsTransfer
          Start-BitsTransfer -Source https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi -Destination SqlLocalDB.msi
          Write-Host "Installing"
          Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
          Write-Host "Checking"
          sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.src-dir}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.src-dir}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.src-dir}}
